name: journal
description: "Photo Journal App"
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.2
  table_calendar: ^3.0.9
  speech_to_text: ^7.0.0
  image_picker: ^1.1.2
  provider: ^6.1.2
  vertical_card_pager: ^1.4.0
  intl: ^0.20.2
  flutter_colorpicker: ^1.0.3
  flutter_image_compress: ^2.4.0 
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/questions/
  uses-material-design: true