// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCYyaixFbFGD-BiTC9Kq44PeL1PqSSimw',
    appId: '1:291215475883:web:30c9a4da1fff024799e3ee',
    messagingSenderId: '291215475883',
    projectId: 'photojournal-a784e',
    authDomain: 'photojournal-a784e.firebaseapp.com',
    storageBucket: 'photojournal-a784e.firebasestorage.app',
    measurementId: 'G-LT83KT3JRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf8tXppix5q1_2xFcdognpVdyAxYkEu1Q',
    appId: '1:291215475883:android:a1df13f8ebe9032499e3ee',
    messagingSenderId: '291215475883',
    projectId: 'photojournal-a784e',
    storageBucket: 'photojournal-a784e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVFrB_7HMBe0G_79vhnMn3zPT_Y8HkkhM',
    appId: '1:291215475883:ios:db015a8781b2328099e3ee',
    messagingSenderId: '291215475883',
    projectId: 'photojournal-a784e',
    storageBucket: 'photojournal-a784e.firebasestorage.app',
    androidClientId: '291215475883-jfhl2jl6ljcga33m7cq0u0dpfv2hfecc.apps.googleusercontent.com',
    iosClientId: '291215475883-ieglohlte0kpb46s918ukl15t3vc5s2h.apps.googleusercontent.com',
    iosBundleId: 'com.mikemac.journal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVFrB_7HMBe0G_79vhnMn3zPT_Y8HkkhM',
    appId: '1:291215475883:ios:2529426f9e4f400499e3ee',
    messagingSenderId: '291215475883',
    projectId: 'photojournal-a784e',
    storageBucket: 'photojournal-a784e.firebasestorage.app',
    androidClientId: '291215475883-jfhl2jl6ljcga33m7cq0u0dpfv2hfecc.apps.googleusercontent.com',
    iosClientId: '291215475883-gpvef8cb5p1d8didqauvt7n2pvtrfmug.apps.googleusercontent.com',
    iosBundleId: 'com.example.journal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCYyaixFbFGD-BiTC9Kq44PeL1PqSSimw',
    appId: '1:291215475883:web:30c9a4da1fff024799e3ee',
    messagingSenderId: '291215475883',
    projectId: 'photojournal-a784e',
    authDomain: 'photojournal-a784e.firebaseapp.com',
    storageBucket: 'photojournal-a784e.firebasestorage.app',
    measurementId: 'G-LT83KT3JRE',
  );

}